### ISSUE TITLE
PDFImage

### ISSUE THREAD

**Issue by IlmadEddine** [jankapunkt/PDFView#6]
Hi ... 

Thank you for your work

I try this ... i am using AdobeFlex 4.6 but a set of errors

com.jankuester.pdfviewer.core.pdfloader.PDFImage 
com.jankuester.pdfviewer.core.model.resources.maps.PatternMap;
StringUtils.reverse

Theses classes is missing !!

**Comment by jankapunkt** [comment]
Hi there, 

thank you for the hint! I am unsure why they are missing but I will add them immediately!

**Comment by jankapunkt** [comment]
Added! please check, if you can build the project now :-)

**Comment by IlmadEddine** [comment]
Great .... Thank you 

I also try with Apache SDK 4.14.1 AIR 17.0 ... it work
